// <auto-generated />
using System;
using GestionnaireBibliotheque.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestionnaireBibliotheque.Infrastructure.Migrations
{
    [DbContext(typeof(BibliothequeContext))]
    [Migration("20260716204640_SeedEmpruntsPenalites")]
    partial class SeedEmpruntsPenalites
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GestionnaireBibliotheque.Infrastructure.Persistence.Models.TableAuteur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Nom");

                    b.ToTable("Auteurs", (string)null);
                });

            modelBuilder.Entity("GestionnaireBibliotheque.Infrastructure.Persistence.Models.TableEmprunt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateEmprunt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("DateRetourPrevue")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateRetourReel")
                        .HasColumnType("datetime2");

                    b.Property<byte>("EtatEmprunt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)0);

                    b.Property<int>("ExemplaireId")
                        .HasColumnType("int");

                    b.Property<int>("MembreId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("DateRetourPrevue");

                    b.HasIndex("ExemplaireId");

                    b.HasIndex("MembreId", "EtatEmprunt");

                    b.ToTable("Emprunts", (string)null);
                });

            modelBuilder.Entity("GestionnaireBibliotheque.Infrastructure.Persistence.Models.TableExemplaire", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("CodeBarre")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<byte>("EtatDisponibilite")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)0);

                    b.Property<int>("OuvrageId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CodeBarre")
                        .IsUnique();

                    b.HasIndex("EtatDisponibilite");

                    b.HasIndex("OuvrageId");

                    b.ToTable("Exemplaires", (string)null);
                });

            modelBuilder.Entity("GestionnaireBibliotheque.Infrastructure.Persistence.Models.TableMembre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateInscription")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte>("TypeAdherentId")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("Nom");

                    b.HasIndex("TypeAdherentId");

                    b.ToTable("Membres", (string)null);
                });

            modelBuilder.Entity("GestionnaireBibliotheque.Infrastructure.Persistence.Models.TableOuvrage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuteurId")
                        .HasColumnType("int");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("AuteurId");

                    b.HasIndex("Titre");

                    b.ToTable("Ouvrages", (string)null);
                });

            modelBuilder.Entity("GestionnaireBibliotheque.Infrastructure.Persistence.Models.TablePenalite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatePenalite")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("EmpruntId")
                        .HasColumnType("int");

                    b.Property<int>("ExemplaireId")
                        .HasColumnType("int");

                    b.Property<int>("JoursRetard")
                        .HasColumnType("int");

                    b.Property<int>("MembreId")
                        .HasColumnType("int");

                    b.Property<decimal>("Montant")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<byte>("Statut")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1);

                    b.HasKey("Id");

                    b.HasIndex("EmpruntId");

                    b.HasIndex("ExemplaireId");

                    b.HasIndex("MembreId");

                    b.ToTable("Penalites", (string)null);
                });

            modelBuilder.Entity("GestionnaireBibliotheque.Infrastructure.Persistence.Models.TableTypeAdherent", b =>
                {
                    b.Property<byte>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<byte>("Id"));

                    b.Property<byte>("DureeEmpruntJours")
                        .HasColumnType("tinyint");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte>("NombreOuvragesMax")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("Libelle")
                        .IsUnique();

                    b.ToTable("TypesAdherent", (string)null);

                    b.HasData(
                        new
                        {
                            Id = (byte)1,
                            DureeEmpruntJours = (byte)21,
                            Libelle = "Adhérent standard",
                            NombreOuvragesMax = (byte)3
                        },
                        new
                        {
                            Id = (byte)2,
                            DureeEmpruntJours = (byte)28,
                            Libelle = "Adhérent étudiant",
                            NombreOuvragesMax = (byte)5
                        });
                });

            modelBuilder.Entity("GestionnaireBibliotheque.Infrastructure.Persistence.Models.TableEmprunt", b =>
                {
                    b.HasOne("GestionnaireBibliotheque.Infrastructure.Persistence.Models.TableExemplaire", null)
                        .WithMany()
                        .HasForeignKey("ExemplaireId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionnaireBibliotheque.Infrastructure.Persistence.Models.TableMembre", null)
                        .WithMany()
                        .HasForeignKey("MembreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GestionnaireBibliotheque.Infrastructure.Persistence.Models.TableExemplaire", b =>
                {
                    b.HasOne("GestionnaireBibliotheque.Infrastructure.Persistence.Models.TableOuvrage", null)
                        .WithMany()
                        .HasForeignKey("OuvrageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GestionnaireBibliotheque.Infrastructure.Persistence.Models.TableMembre", b =>
                {
                    b.HasOne("GestionnaireBibliotheque.Infrastructure.Persistence.Models.TableTypeAdherent", null)
                        .WithMany()
                        .HasForeignKey("TypeAdherentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GestionnaireBibliotheque.Infrastructure.Persistence.Models.TableOuvrage", b =>
                {
                    b.HasOne("GestionnaireBibliotheque.Infrastructure.Persistence.Models.TableAuteur", null)
                        .WithMany()
                        .HasForeignKey("AuteurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GestionnaireBibliotheque.Infrastructure.Persistence.Models.TablePenalite", b =>
                {
                    b.HasOne("GestionnaireBibliotheque.Infrastructure.Persistence.Models.TableExemplaire", null)
                        .WithMany()
                        .HasForeignKey("ExemplaireId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionnaireBibliotheque.Infrastructure.Persistence.Models.TableMembre", null)
                        .WithMany()
                        .HasForeignKey("MembreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
